# OpenUPM azure pipelines
name: azure-pipelines-test

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm --version
    node --version
  displayName: 'Display npm version'

# - script: sudo npm install -g npm
#   displayName: 'Upgrade npm version'

- task: Npm@1
  inputs:
    command: custom
    customCommand: 'install -g npm@8.7.0'
  displayName: 'Upgrade npm to v8.7.0'

- script: |
    npm --version
    node --version
  displayName: 'Display npm version'

- task: Npm@1
  inputs:
    command: custom
    customCommand: 'pack --dry-run'
  displayName: 'Npm pack dry run'
